item: list[str] = [
    "No Item",
	"Poke Ball",
	"Great Ball",
	"Ultra Ball",
	"Master Ball",
	"Premier Ball",
	"Heal Ball",
	"Net Ball",
	"Nest Ball",
	"Dive Ball",
	"Dusk Ball",
	"Timer Ball",
	"Quick Ball",
	"Repeat Ball",
	"Luxury Ball",
	"Level Ball",
	"Lure Ball",
	"Moon Ball",
	"Friend Ball",
	"Love Ball",
	"Fast Ball",
	"Heavy Ball",
	"Dream Ball",
	"Safari Ball",
	"Sport Ball",
	"Park Ball",
	"Beast Ball",
	"Cherish Ball",
	"Potion",
	"Super Potion",
	"Hyper Potion",
	"Max Potion",
	"Full Restore",
	"Revive",
	"Max Revive",
	"Fresh Water",
	"Soda Pop",
	"Lemonade",
	"Moomoo Milk",
	"Energy Powder",
	"Energy Root",
	"Heal Powder",
	"Revival Herb",
	"Antidote",
	"Paralyze Heal",
	"Burn Heal",
	"Ice Heal",
	"Awakening",
	"Full Heal",
	"Ether",
	"Max Ether",
	"Elixir",
	"Max Elixir",
	"Berry Juice",
	"Sacred Ash",
	"Sweet Heart",
	"Max Honey",
	"Pewter Crunchies",
	"Rage Candy Bar",
	"Lava Cookie",
	"Old Gateau",
	"Casteliacone",
	"Lumiose Galette",
	"Shalour Sable",
	"Big Malasada",
	"Hp Up",
	"Protein",
	"Iron",
	"Calcium",
	"Zinc",
	"Carbos",
	"Pp Up",
	"Pp Max",
	"Health Wing",
	"Muscle Wing",
	"Resist Wing",
	"Genius Wing",
	"Clever Wing",
	"Swift Wing",
	"Ability Capsule",
	"Ability Patch",
	"Lonely Mint",
	"Adamant Mint",
	"Naughty Mint",
	"Brave Mint",
	"Bold Mint",
	"Impish Mint",
	"Lax Mint",
	"Relaxed Mint",
	"Modest Mint",
	"Mild Mint",
	"Rash Mint",
	"Quiet Mint",
	"Calm Mint",
	"Gentle Mint",
	"Careful Mint",
	"Sassy Mint",
	"Timid Mint",
	"Hasty Mint",
	"Jolly Mint",
	"Naive Mint",
	"Serious Mint",
	"Rare Candy",
	"Exp Candy Xs",
	"Exp Candy S",
	"Exp Candy M",
	"Exp Candy L",
	"Exp Candy Xl",
	"Dynamax Candy",
	"Blue Flute",
	"Yellow Flute",
	"Red Flute",
	"Black Flute",
	"White Flute",
	"Repel",
	"Super Repel",
	"Max Repel",
	"Lure",
	"Super Lure",
	"Max Lure",
	"Escape Rope",
	"X Attack",
	"X Defense",
	"X Sp Atk",
	"X Sp Def",
	"X Speed",
	"X Accuracy"
	"Dire Hit",
	"Guard Spec",
	"Poke Doll",
	"Fluffy Tail",
	"Poke Toy",
	"Max Mushrooms",
	"Bottle Cap",
	"Gold Bottle Cap",
	"Nugget",
	"Big Nugget",
	"Tiny Mushroom",
	"Big Mushroom",
	"Balm Mushroom",
	"Pearl",
	"Big Pearl",
	"Pearl String",
	"Stardust",
	"Star Piece",
	"Comet Shard",
	"Shoal Salt",
	"Shoal Shell",
	"Red Shard",
	"Blue Shard",
	"Yellow Shard",
	"Green Shard",
	"Heart Scale",
	"Honey",
	"Rare Bone",
	"Odd Keystone",
	"Pretty Feather",
	"Relic Copper",
	"Relic Silver",
	"Relic Gold",
	"Relic Vase",
	"Relic Band",
	"Relic Statue",
	"Relic Crown",
	"Strange Souvenir",
	"Helix Fossil",
	"Dome Fossil",
	"Old Amber",
	"Root Fossil",
	"Claw Fossil",
	"Armor Fossil",
	"Skull Fossil",
	"Cover Fossil",
	"Plume Fossil",
	"Jaw Fossil",
	"Sail Fossil",
	"Fossilized Bird",
	"Fossilized Fish",
	"Fossilized Drake",
	"Fossilized Dino",
	"Growth Mulch",
	"Damp Mulch",
	"Stable Mulch",
	"Gooey Mulch",
	"Rich Mulch",
	"Surprise Mulch",
	"Boost Mulch",
	"Amaze Mulch",
	"Red Apricorn",
	"Blue Apricorn",
	"Yellow Apricorn",
	"Green Apricorn",
	"Pink Apricorn",
	"White Apricorn",
	"Black Apricorn",
	"Wishing Piece",
	"Galarica Twig",
	"Armorite Ore",
	"Dynite Ore",
	"Orange Mail",
	"Harbor Mail",
	"Glitter Mail",
	"Mech Mail",
	"Wood Mail",
	"Wave Mail",
	"Bead Mail",
	"Shadow Mail",
	"Tropic Mail",
	"Dream Mail",
	"Fab Mail",
	"Retro Mail",
	"Fire Stone",
	"Water Stone",
	"Thunder Stone",
	"Leaf Stone",
	"Ice Stone",
	"Sun Stone",
	"Moon Stone",
	"Shiny Stone",
	"Dusk Stone",
	"Dawn Stone",
	"Sweet Apple",
	"Tart Apple",
	"Cracked Pot",
	"Chipped Pot",
	"Galarica Cuff",
	"Galarica Wreath",
	"Dragon Scale",
	"Up Grade",
	"Protector",
	"Electirizer",
	"Magmarizer",
	"Dubious Disc",
	"Reaper Cloth",
	"Prism Scale",
	"Whipped Dream",
	"Sachet",
	"Oval Stone",
	"Strawberry Sweet",
	"Love Sweet",
	"Berry Sweet",
	"Clover Sweet",
	"Flower Sweet",
	"Star Sweet",
	"Ribbon Sweet"
	"Everstone",
	"Red Nectar",
	"Yellow Nectar",
	"Pink Nectar",
	"Purple Nectar",
	"Flame Plate",
	"Splash Plate",
	"Zap Plate",
	"Meadow Plate",
	"Icicle Plate",
	"Fist Plate",
	"Toxic Plate",
	"Earth Plate",
	"Sky Plate",
	"Mind Plate",
	"Insect Plate",
	"Stone Plate",
	"Spooky Plate",
	"Draco Plate",
	"Dread Plate",
	"Iron Plate",
	"Pixie Plate",
	"Douse Drive",
	"Shock Drive",
	"Burn Drive",
	"Chill Drive",
	"Fire Memory",
	"Water Memory",
	"Electric Memory",
	"Grass Memory",
	"Ice Memory",
	"Fighting Memory",
	"Poison Memory",
	"Ground Memory",
	"Flying Memory",
	"Psychic Memory",
	"Bug Memory",
	"Rock Memory",
	"Ghost Memory",
	"Dragon Memory",
	"Dark Memory",
	"Steel Memory",
	"Fairy Memory"
	"Rusted Sword",
	"Rusted Shield",
	"Red Orb",
	"Blue Orb",
	"Venusaurite",
	"Charizardite X",
	"Charizardite Y",
	"Blastoisinite",
	"Beedrillite",
	"Pidgeotite",
	"Alakazite",
	"Slowbronite",
	"Gengarite",
	"Kangaskhanite",
	"Pinsirite",
	"Gyaradosite",
	"Aerodactylite",
	"Mewtwonite X",
	"Mewtwonite Y",
	"Ampharosite",
	"Steelixite",
	"Scizorite",
	"Heracronite",
	"Houndoominite",
	"Tyranitarite",
	"Sceptilite",
	"Blazikenite",
	"Swampertite",
	"Gardevoirite",
	"Sablenite",
	"Mawilite",
	"Aggronite",
	"Medichamite",
	"Manectite",
	"Sharpedonite",
	"Cameruptite",
	"Altarianite",
	"Banettite",
	"Absolite",
	"Glalitite",
	"Salamencite",
	"Metagrossite",
	"Latiasite",
	"Latiosite",
	"Lopunnite",
	"Garchompite",
	"Lucarionite",
	"Abomasite",
	"Galladite",
	"Audinite",
	"Diancite",
	"Normal Gem",
	"Fire Gem",
	"Water Gem",
	"Electric Gem",
	"Grass Gem",
	"Ice Gem",
	"Fighting Gem",
	"Poison Gem",
	"Ground Gem",
	"Flying Gem",
	"Psychic Gem",
	"Bug Gem",
	"Rock Gem",
	"Ghost Gem",
	"Dragon Gem",
	"Dark Gem",
	"Steel Gem",
	"Fairy Gem",
	"Normalium Z",
	"Firium Z",
	"Waterium Z",
	"Electrium Z",
	"Grassium Z",
	"Icium Z",
	"Fightinium Z",
	"Poisonium Z",
	"Groundium Z",
	"Flyinium Z",
	"Psychium Z",
	"Buginium Z",
	"Rockium Z",
	"Ghostium Z",
	"Dragonium Z",
	"Darkinium Z",
	"Steelium Z",
	"Fairium Z",
	"Pikanium Z",
	"Eevium Z",
	"Snorlium Z",
	"Mewnium Z",
	"Decidium Z",
	"Incinium Z",
	"Primarium Z",
	"Lycanium Z",
	"Mimikium Z",
	"Kommonium Z",
	"Tapunium Z",
	"Solganium Z",
	"Lunalium Z",
	"Marshadium Z",
	"Aloraichium Z",
	"Pikashunium Z",
	"Ultranecrozium Z",
	"Light Ball",
	"Stick",
	"Thick Club",
	"Lucky Punch",
	"Metal Powder",
	"Quick Powder",
	"Deep Sea Scale",
	"Deep Sea Tooth",
	"Soul Dew",
	"Adamant Orb",
	"Lustrous Orb",
	"Griseous Orb",
	"Sea Incense",
	"Lax Incense",
	"Odd Incense",
	"Rock Incense",
	"Full Incense",
	"Wave Incense",
	"Rose Incense",
	"Luck Incense",
	"Pure Incense",
	"Red Scarf",
	"Blue Scarf",
	"Pink Scarf",
	"Green Scarf",
	"Yellow Scarf",
	"Macho Brace",
	"Power Weight",
	"Power Bracer",
	"Power Belt",
	"Power Lens",
	"Power Band",
	"Power Anklet",
	"Silk Scarf",
	"Charcoal",
	"Mystic Water",
	"Magnet",
	"Miracle Seed",
	"Never Melt Ice",
	"Black Belt",
	"Blackbelt",
	"Poison Barb",
	"Soft Sand",
	"Sharp Beak",
	"Twisted Spoon",
	"Silver Powder",
	"Hard Stone",
	"Spell Tag",
	"Dragon Fang",
	"Black Glasses",
	"Metal Coat",
	"Choice Band",
	"Choice Specs",
	"Choice Scarf",
	"Flame Orb",
	"Toxic Orb",
	"Damp Rock",
	"Heat Rock",
	"Smooth Rock",
	"Icy Rock",
	"Electric Seed",
	"Psychic Seed",
	"Misty Seed",
	"Grassy Seed",
	"Absorb Bulb",
	"Cell Battery",
	"Luminous Moss",
	"Snowball",
	"Bright Powder",
	"White Herb",
	"Exp Share",
	"Quick Claw",
	"Soothe Bell",
	"Mental Herb",
	"Kings Rock",
	"Amulet Coin",
	"Cleanse Tag",
	"Smoke Ball",
	"Focus Band",
	"Lucky Egg",
	"Scope Lens",
	"Leftovers",
	"Shell Bell",
	"Wide Lens",
	"Muscle Band",
	"Wise Glasses",
	"Expert Belt",
	"Light Clay",
	"Life Orb",
	"Power Herb",
	"Focus Sash",
	"Zoom Lens",
	"Metronome",
	"Iron Ball",
	"Lagging Tail",
	"Destiny Knot",
	"Black Sludge",
	"Grip Claw",
	"Sticky Barb",
	"Shed Shell",
	"Big Root",
	"Razor Claw",
	"Razor Fang",
	"Eviolite",
	"Float Stone",
	"Rocky Helmet",
	"Air Balloon",
	"Red Card",
	"Ring Target",
	"Binding Band",
	"Eject Button",
	"Weakness Policy",
	"Assault Vest",
	"Safety Goggles",
	"Adrenaline Orb",
	"Terrain Extender",
	"Protective Pads",
	"Throat Spray",
	"Eject Pack",
	"Heavy Duty Boots",
	"Blunder Policy",
	"Room Service",
	"Utility Umbrella",
	"Cheri Berry",
	"Chesto Berry",
	"Pecha Berry",
	"Rawst Berry",
	"Aspear Berry",
	"Leppa Berry",
	"Oran Berry",
	"Persim Berry",
	"Lum Berry",
	"Sitrus Berry",
	"Figy Berry",
	"Wiki Berry",
	"Mago Berry",
	"Aguav Berry",
	"Iapapa Berry",
	"Razz Berry",
	"Bluk Berry",
	"Nanab Berry",
	"Wepear Berry",
	"Pinap Berry",
	"Pomeg Berry",
	"Kelpsy Berry",
	"Qualot Berry",
	"Hondew Berry",
	"Grepa Berry",
	"Tamato Berry",
	"Cornn Berry",
	"Magost Berry",
	"Rabuta Berry",
	"Nomel Berry",
	"Spelon Berry",
	"Pamtre Berry",
	"Watmel Berry",
	"Durin Berry",
	"Belue Berry",
	"Chilan Berry",
	"Occa Berry",
	"Passho Berry",
	"Wacan Berry",
	"Rindo Berry",
	"Yache Berry",
	"Chople Berry",
	"Kebia Berry",
	"Shuca Berry",
	"Coba Berry",
	"Payapa Berry",
	"Tanga Berry",
	"Charti Berry",
	"Kasib Berry",
	"Haban Berry",
	"Colbur Berry",
	"Babiri Berry",
	"Roseli Berry",
	"Liechi Berry",
	"Ganlon Berry",
	"Salac Berry",
	"Petaya Berry",
	"Apicot Berry",
	"Lansat Berry",
	"Starf Berry",
	"Enigma Berry",
	"Micle Berry",
	"Custap Berry",
	"Jaboca Berry",
	"Rowap Berry",
	"Kee Berry",
	"Maranga Berry",
	"Enigma Berry E Reader",
	"Tm01",
	"Tm02",
	"Tm03",
	"Tm04",
	"Tm05",
	"Tm06",
	"Tm07",
	"Tm08",
	"Tm09",
	"Tm10",
	"Tm11",
	"Tm12",
	"Tm13",
	"Tm14",
	"Tm15",
	"Tm16",
	"Tm17",
	"Tm18",
	"Tm19",
	"Tm20",
	"Tm21",
	"Tm22",
	"Tm23",
	"Tm24",
	"Tm25",
	"Tm26",
	"Tm27",
	"Tm28",
	"Tm29",
	"Tm30",
	"Tm31",
	"Tm32",
	"Tm33",
	"Tm34",
	"Tm35",
	"Tm36",
	"Tm37",
	"Tm38",
	"Tm39",
	"Tm40",
	"Tm41",
	"Tm42",
	"Tm43",
	"Tm44",
	"Tm45",
	"Tm46",
	"Tm47",
	"Tm48",
	"Tm49",
	"Tm50",
	"Tm51",
	"Tm52",
	"Tm53",
	"Tm54",
	"Tm55",
	"Tm56",
	"Tm57",
	"Tm58",
	"Tm59",
	"Tm60",
	"Tm61",
	"Tm62",
	"Tm63",
	"Tm64",
	"Tm65",
	"Tm66",
	"Tm67",
	"Tm68",
	"Tm69",
	"Tm70",
	"Tm71",
	"Tm72",
	"Tm73",
	"Tm74",
	"Tm75",
	"Tm76",
	"Tm77",
	"Tm78",
	"Tm79",
	"Tm80",
	"Tm81",
	"Tm82",
	"Tm83",
	"Tm84",
	"Tm85",
	"Tm86",
	"Tm87",
	"Tm88",
	"Tm89",
	"Tm90",
	"Tm91",
	"Tm92",
	"Tm93",
	"Tm94",
	"Tm95",
	"Tm96",
	"Tm97",
	"Tm98",
	"Tm99",
	"Tm100",
	"Hm01",
	"Hm02",
	"Hm03",
	"Hm04",
	"Hm05",
	"Hm06",
	"Hm07",
	"Hm08",
	"Oval Charm",
	"Shiny Charm",
	"Catching Charm",
	"Exp Charm",
	"Rotom Catalog",
	"Gracidea",
	"Reveal Glass",
	"Dna Splicers",
	"Zygarde Cube",
	"Prison Bottle",
	"N Solarizer",
	"N Lunarizer",
	"Reins Of Unity",
	"Mega Ring",
	"Z Power Ring",
	"Dynamax Band",
	"Bicycle",
	"Mach Bike",
	"Acro Bike",
	"Old Rod",
	"Good Rod",
	"Super Rod",
	"Itemfinder",
	"Town Map",
	"Vs Seeker",
	"Tm Case",
	"Berry Pouch",
	"Pokemon Box",
	"Coin Case",
	"Powder Jar",
	"Wailmer Pail",
	"Poke Radar",
	"Pokeblock Case",
	"Soot Sack",
	"Poke Flute",
	"Fame Checker",
	"Teachy Tv",
	"Ss Ticket",
	"Eon Ticket",
	"Mystic Ticket",
	"Aurora Ticket",
	"Old Sea Map",
	"Letter",
	"Devon Goods",
	"Go Goggles",
	"Devon Scope",
	"Basement Key",
	"Scanner",
	"Storage Key",
	"Rm 1 Key",
	"Rm 2 Key",
	"Rm 4 Key",
	"Rm 6 Key",
	"Meteorite",
	"Magma Emblem",
	"Contest Pass",
	"Oaks Parcel",
	"Secret Key",
	"Bike Voucher",
	"Gold Teeth",
	"Card Key",
	"Lift Key",
	"Silph Scope",
	"Tri Pass",
	"Rainbow Pass",
	"Tea",
	"Ruby",
	"Sapphire",
	"Ability Shield",
	"Clear Amulet",
	"Punching Glove",
	"Covert Cloak",
	"Loaded Dice",
	"Auspicious Armor",
	"Booster Energy",
	"Big Bamboo Shoot",
	"Gimmighoul Coin",
	"Leaders Crest",
	"Malicious Armor",
	"Mirror Herb",
	"Scroll Of Darkness",
	"Scroll Of Waters",
	"Tera Orb",
	"Tiny Bamboo Shoot",
	"Bug Tera Shard",
	"Dark Tera Shard",
	"Dragon Tera Shard",
	"Electric Tera Shard",
	"Fairy Tera Shard",
	"Fighting Tera Shard",
	"Fire Tera Shard",
	"Flying Tera Shard",
	"Ghost Tera Shard",
	"Grass Tera Shard",
	"Ground Tera Shard",
	"Ice Tera Shard",
	"Normal Tera Shard",
	"Poison Tera Shard",
	"Psychic Tera Shard",
	"Rock Tera Shard",
	"Steel Tera Shard",
	"Water Tera Shard",
	"Adamant Crystal",
	"Griseous Core",
	"Lustrous Globe",
	"Black Augurite",
	"Linking Cord",
	"Peat Block",
	"Berserk Gene",
	"Fairy Feather",
	"Syrupy Apple",
	"Unremarkable Teacup",
	"Masterpiece Teacup",
	"Cornerstone Mask",
	"Wellspring Mask",
	"Hearthflame Mask",
	"Health Mochi",
	"Muscle Mochi",
	"Resist Mochi",
	"Genius Mochi",
	"Clever Mochi",
	"Swift Mochi",
	"Fresh Start Mochi",
	"Glimmering Charm",
	"Metal Alloy",
	"Stellar Tera Shard",
    "Jubilife Muffin",
	"Remedy",
	"Fine Remedy",
	"Superb Remedy",
	"Aux Evasion",
	"Aux Guard",
	"Aux Power",
	"Aux Powerguard",
	"Choice Dumpling",
	"Swap Snack",
	"Twice Spiced Radish",
	"Pokeshi Doll",
	"Strange Ball",
	"Clefablite",
	"Victreebelite",
	"Starminite",
	"Dragoninite",
	"Meganiumite",
	"Feraligite",
	"Skarmorite",
	"Froslassite",
	"Emboarite",
	"Excadrite",
	"Scolipite",
	"Scraftinite",
	"Eelektrossite",
	"Chandelurite",
	"Chesnaughtite",
	"Delphoxite",
	"Greninjite",
	"Pyroarite",
	"Floettite",
	"Malamarite",
	"Barbaracite",
	"Dragalgite",
	"Hawluchanite",
	"Zygardite",
	"Drampanite",
	"Falinksite"
]

nature: list[str] = [
	"Hardy",
	"Lonely",
	"Brave",
	"Adamant",
	"Naughty",
	"Bold",
	"Docile",
	"Relaxed",
	"Impish",
	"Lax",
	"Timid",
	"Hasty",
	"Serious",
	"Jolly",
	"Naive",
	"Modest",
	"Mild",
	"Quiet",
	"Bashful",
	"Rash",
	"Calm",
	"Gentle",
	"Sassy",
	"Careful",
	"Quirky"
]

ability: list[str] = [
    "None",
	"Stench",
	"Drizzle",
	"Speed Boost",
	"Battle Armor",
	"Sturdy",
	"Damp",
	"Limber",
	"Sand Veil",
	"Static",
	"Volt Absorb",
	"Water Absorb",
	"Oblivious",
	"Cloud Nine",
	"Compound Eyes",
	"Insomnia",
	"Color Change",
	"Immunity",
	"Flash Fire",
	"Shield Dust",
	"Own Tempo",
	"Suction Cups",
	"Intimidate",
	"Shadow Tag",
	"Rough Skin",
	"Wonder Guard",
	"Levitate",
	"Effect Spore",
	"Synchronize",
	"Clear Body",
	"Natural Cure",
	"Lightning Rod",
	"Serene Grace",
	"Swift Swim",
	"Chlorophyll",
	"Illuminate",
	"Trace",
	"Huge Power",
	"Poison Point",
	"Inner Focus",
	"Magma Armor",
	"Water Veil",
	"Magnet Pull",
	"Soundproof",
	"Rain Dish",
	"Sand Stream",
	"Pressure",
	"Thick Fat",
	"Early Bird",
	"Flame Body",
	"Run Away",
	"Keen Eye",
	"Hyper Cutter",
	"Pickup",
	"Truant",
	"Hustle",
	"Cute Charm",
	"Plus",
	"Minus",
	"Forecast",
	"Sticky Hold",
	"Shed Skin",
	"Guts",
	"Marvel Scale",
	"Liquid Ooze",
	"Overgrow",
	"Blaze",
	"Torrent",
	"Swarm",
	"Rock Head",
	"Drought",
	"Arena Trap",
	"Vital Spirit",
	"White Smoke",
	"Pure Power",
	"Shell Armor",
	"Air Lock",
	"Tangled Feet",
	"Motor Drive",
	"Rivalry",
	"Steadfast",
	"Snow Cloak",
	"Gluttony",
	"Anger Point",
	"Unburden",
	"Heatproof",
	"Simple",
	"Dry Skin",
	"Download",
	"Iron Fist",
	"Poison Heal",
	"Adaptability",
	"Skill Link",
	"Hydration",
	"Solar Power",
	"Quick Feet",
	"Normalize",
	"Sniper",
	"Magic Guard",
	"No Guard",
	"Stall",
	"Technician",
	"Leaf Guard",
	"Klutz",
	"Mold Breaker",
	"Super Luck",
	"Aftermath",
	"Anticipation",
	"Forewarn",
	"Unaware",
	"Tinted Lens",
	"Filter",
	"Slow Start",
	"Scrappy",
	"Storm Drain",
	"Ice Body",
	"Solid Rock",
	"Snow Warning",
	"Honey Gather",
	"Frisk",
	"Reckless",
	"Multitype",
	"Flower Gift",
	"Bad Dreams",
	"Pickpocket",
	"Sheer Force",
	"Contrary",
	"Unnerve",
	"Defiant",
	"Defeatist",
	"Cursed Body",
	"Healer",
	"Friend Guard",
	"Weak Armor",
	"Heavy Metal",
	"Light Metal",
	"Multiscale",
	"Toxic Boost",
	"Flare Boost",
	"Harvest",
	"Telepathy",
	"Moody",
	"Overcoat",
	"Poison Touch",
	"Regenerator",
	"Big Pecks",
	"Sand Rush",
	"Wonder Skin",
	"Analytic",
	"Illusion",
	"Imposter",
	"Infiltrator",
	"Mummy",
	"Moxie",
	"Justified",
	"Rattled",
	"Magic Bounce",
	"Sap Sipper",
	"Prankster",
	"Sand Force",
	"Iron Barbs",
	"Zen Mode",
	"Victory Star",
	"Turboblaze",
	"Teravolt",
	"Aroma Veil",
	"Flower Veil",
	"Cheek Pouch",
	"Protean",
	"Fur Coat",
	"Magician",
	"Bulletproof",
	"Competitive",
	"Strong Jaw",
	"Refrigerate",
	"Sweet Veil",
	"Stance Change",
	"Gale Wings",
	"Mega Launcher",
	"Grass Pelt",
	"Symbiosis",
	"Tough Claws",
	"Pixilate",
	"Gooey",
	"Aerilate",
	"Parental Bond",
	"Dark Aura",
	"Fairy Aura",
	"Aura Break",
	"Primordial Sea",
	"Desolate Land",
	"Delta Stream",
	"Stamina",
	"Wimp Out",
	"Emergency Exit",
	"Water Compaction",
	"Merciless",
	"Shields Down",
	"Stakeout",
	"Water Bubble",
	"Steelworker",
	"Berserk",
	"Slush Rush",
	"Long Reach",
	"Liquid Voice",
	"Triage",
	"Galvanize",
	"Surge Surfer",
	"Schooling",
	"Disguise",
	"Battle Bond",
	"Power Construct",
	"Corrosion",
	"Comatose",
	"Queenly Majesty",
	"Innards Out",
	"Dancer",
	"Battery",
	"Fluffy",
	"Dazzling",
	"Soul Heart",
	"Tangling Hair",
	"Receiver",
	"Power Of Alchemy",
	"Beast Boost",
	"Rks System",
	"Electric Surge",
	"Psychic Surge",
	"Misty Surge",
	"Grassy Surge",
	"Full Metal Body",
	"Shadow Shield",
	"Prism Armor",
	"Neuroforce",
	"Intrepid Sword",
	"Dauntless Shield",
	"Libero",
	"Ball Fetch",
	"Cotton Down",
	"Propeller Tail",
	"Mirror Armor",
	"Gulp Missile",
	"Stalwart",
	"Steam Engine",
	"Punk Rock",
	"Sand Spit",
	"Ice Scales",
	"Ripen",
	"Ice Face",
	"Power Spot",
	"Mimicry",
	"Screen Cleaner",
	"Steely Spirit",
	"Perish Body",
	"Wandering Spirit",
	"Gorilla Tactics",
	"Neutralizing Gas",
	"Pastel Veil",
	"Hunger Switch",
	"Quick Draw",
	"Unseen Fist",
	"Curious Medicine",
	"Transistor",
	"Dragons Maw",
	"Chilling Neigh",
	"Grim Neigh",
	"As One Ice Rider",
	"As One Shadow Rider",
	"Lingering Aroma",
	"Seed Sower",
	"Thermal Exchange",
	"Anger Shell",
	"Purifying Salt",
	"Well Baked Body",
	"Wind Rider",
	"Guard Dog",
	"Rocky Payload",
	"Wind Power",
	"Zero To Hero",
	"Commander",
	"Electromorphosis",
	"Protosynthesis",
	"Quark Drive",
	"Good As Gold",
	"Vessel Of Ruin",
	"Sword Of Ruin",
	"Tablets Of Ruin",
	"Beads Of Ruin",
	"Orichalcum Pulse",
	"Hadron Engine",
	"Opportunist",
	"Cud Chew",
	"Sharpness",
	"Supreme Overlord",
	"Costar",
	"Toxic Debris",
	"Armor Tail",
	"Earth Eater",
	"Mycelium Might",
	"Hospitality",
	"Minds Eye",
	"Embody Aspect Teal Mask",
	"Embody Aspect Hearthflame Mask",
	"Embody Aspect Wellspring Mask",
	"Embody Aspect Cornerstone Mask",
	"Toxic Chain",
	"Supersweet Syrup",
	"Tera Shift",
	"Tera Shell",
	"Teraform Zero",
	"Poison Puppeteer"
]

move_name: list[str] = [
    "???",
    "Pound",
	"Karate Chop",
	"Double Slap",
	"Comet Punch",
	"Mega Punch",
	"Pay Day",
	"Fire Punch",
	"Ice Punch",
	"Thunder Punch",
	"Scratch",
	"Vise Grip",
	"Guillotine",
	"Razor Wind",
	"Swords Dance",
	"Cut",
	"Gust",
	"Wing Attack",
	"Whirlwind",
	"Fly",
	"Bind",
	"Slam",
	"Vine Whip",
	"Stomp",
	"Double Kick",
	"Mega Kick",
	"Jump Kick",
	"Rolling Kick",
	"Sand Attack",
	"Headbutt",
	"Horn Attack",
	"Fury Attack",
	"Horn Drill",
	"Tackle",
	"Body Slam",
	"Wrap",
	"Take Down",
	"Thrash",
	"Double-Edge",
	"Tail Whip",
	"Poison Sting",
	"Twineedle",
	"Pin Missile",
	"Leer",
	"Bite",
	"Growl",
	"Roar",
	"Sing",
	"Supersonic",
	"Sonic Boom",
	"Disable",
	"Acid",
	"Ember",
	"Flamethrower",
	"Mist",
	"Water Gun",
	"Hydro Pump",
	"Surf",
	"Ice Beam",
	"Blizzard",
	"Psybeam",
	"Bubble Beam",
	"Aurora Beam",
	"Hyper Beam",
	"Peck",
	"Drill Peck",
	"Submission",
	"Low Kick",
	"Counter",
	"Seismic Toss",
	"Strength",
	"Absorb",
	"Mega Drain",
	"Leech Seed",
	"Growth",
	"Razor Leaf",
	"Solar Beam",
	"Poison Powder",
	"Stun Spore",
	"Sleep Powder",
	"Petal Dance",
	"String Shot",
	"Dragon Rage",
	"Fire Spin",
	"Thunder Shock",
	"Thunderbolt",
	"Thunder Wave",
	"Thunder",
	"Rock Throw",
	"Earthquake",
	"Fissure",
	"Dig",
	"Toxic",
	"Confusion",
	"Psychic",
	"Hypnosis",
	"Meditate",
	"Agility",
	"Quick Attack",
	"Rage",
	"Teleport",
	"Night Shade",
	"Mimic",
	"Screech",
	"Double Team",
	"Recover",
	"Harden",
	"Minimize",
	"Smokescreen",
	"Confuse Ray",
	"Withdraw",
	"Defense Curl",
	"Barrier",
	"Light Screen",
	"Haze",
	"Reflect",
	"Focus Energy",
	"Bide",
	"Metronome",
	"Mirror Move",
	"Self-Destruct",
	"Egg Bomb",
	"Lick",
	"Smog",
	"Sludge",
	"Bone Club",
	"Fire Blast",
	"Waterfall",
	"Clamp",
	"Swift",
	"Skull Bash",
	"Spike Cannon",
	"Constrict",
	"Amnesia",
	"Kinesis",
	"Soft-Boiled",
	"High Jump Kick",
	"Glare",
	"Dream Eater",
	"Poison Gas",
	"Barrage",
	"Leech Life",
	"Lovely Kiss",
	"Sky Attack",
	"Transform",
	"Bubble",
	"Dizzy Punch",
	"Spore",
	"Flash",
	"Psywave",
	"Splash",
	"Acid Armor",
	"Crabhammer",
	"Explosion",
	"Fury Swipes",
	"Bonemerang",
	"Rest",
	"Rock Slide",
	"Hyper Fang",
	"Sharpen",
	"Conversion",
	"Tri Attack",
	"Super Fang",
	"Slash",
	"Substitute",
	"Struggle",
	"Sketch",
	"Triple Kick",
	"Thief",
	"Spider Web",
	"Mind Reader",
	"Nightmare",
	"Flame Wheel",
	"Snore",
	"Curse",
	"Flail",
	"Conversion 2",
	"Aeroblast",
	"Cotton Spore",
	"Reversal",
	"Spite",
	"Powder Snow",
	"Protect",
	"Mach Punch",
	"Scary Face",
	"Feint Attack",
	"Sweet Kiss",
	"Belly Drum",
	"Sludge Bomb",
	"Mud-Slap",
	"Octazooka",
	"Spikes",
	"Zap Cannon",
	"Foresight",
	"Destiny Bond",
	"Perish Song",
	"Icy Wind",
	"Detect",
	"Bone Rush",
	"Lock-On",
	"Outrage",
	"Sandstorm",
	"Giga Drain",
	"Endure",
	"Charm",
	"Rollout",
	"False Swipe",
	"Swagger",
	"Milk Drink",
	"Spark",
	"Fury Cutter",
	"Steel Wing",
	"Mean Look",
	"Attract",
	"Sleep Talk",
	"Heal Bell",
	"Return",
	"Present",
	"Frustration",
	"Safeguard",
	"Pain Split",
	"Sacred Fire",
	"Magnitude",
	"Dynamic Punch",
	"Megahorn",
	"Dragon Breath",
	"Baton Pass",
	"Encore",
	"Pursuit",
	"Rapid Spin",
	"Sweet Scent",
	"Iron Tail",
	"Metal Claw",
	"Vital Throw",
	"Morning Sun",
	"Synthesis",
	"Moonlight",
	"Hidden Power",
	"Cross Chop",
	"Twister",
	"Rain Dance",
	"Sunny Day",
	"Crunch",
	"Mirror Coat",
	"Psych Up",
	"Extreme Speed",
	"Ancient Power",
	"Shadow Ball",
	"Future Sight",
	"Rock Smash",
	"Whirlpool",
	"Beat Up",
	"Fake Out",
	"Uproar",
	"Stockpile",
	"Spit Up",
	"Swallow",
	"Heat Wave",
	"Hail",
	"Torment",
	"Flatter",
	"Will-O-Wisp",
	"Memento",
	"Facade",
	"Focus Punch",
	"Smelling Salts",
	"Follow Me",
	"Nature Power",
	"Charge",
	"Taunt",
	"Helping Hand",
	"Trick",
	"Role Play",
	"Wish",
	"Assist",
	"Ingrain",
	"Superpower",
	"Magic Coat",
	"Recycle",
	"Revenge",
	"Brick Break",
	"Yawn",
	"Knock Off",
	"Endeavor",
	"Eruption",
	"Skill Swap",
	"Imprison",
	"Refresh",
	"Grudge",
	"Snatch",
	"Secret Power",
	"Dive",
	"Arm Thrust",
	"Camouflage",
	"Tail Glow",
	"Luster Purge",
	"Mist Ball",
	"Feather Dance",
	"Teeter Dance",
	"Blaze Kick",
	"Mud Sport",
	"Ice Ball",
	"Needle Arm",
	"Slack Off",
	"Hyper Voice",
	"Poison Fang",
	"Crush Claw",
	"Blast Burn",
	"Hydro Cannon",
	"Meteor Mash",
	"Astonish",
	"Weather Ball",
	"Aromatherapy",
	"Fake Tears",
	"Air Cutter",
	"Overheat",
	"Odor Sleuth",
	"Rock Tomb",
	"Silver Wind",
	"Metal Sound",
	"Grass Whistle",
	"Tickle",
	"Cosmic Power",
	"Water Spout",
	"Signal Beam",
	"Shadow Punch",
	"Extrasensory",
	"Sky Uppercut",
	"Sand Tomb",
	"Sheer Cold",
	"Muddy Water",
	"Bullet Seed",
	"Aerial Ace",
	"Icicle Spear",
	"Iron Defense",
	"Block",
	"Howl",
	"Dragon Claw",
	"Frenzy Plant",
	"Bulk Up",
	"Bounce",
	"Mud Shot",
	"Poison Tail",
	"Covet",
	"Volt Tackle",
	"Magical Leaf",
	"Water Sport",
	"Calm Mind",
	"Leaf Blade",
	"Dragon Dance",
	"Rock Blast",
	"Shock Wave",
	"Water Pulse",
	"Doom Desire",
	"Psycho Boost"
]

### list of all pokemon names in order of id (according to pokeemerald-expansion's ids) up until gen 3
pokemon: list[str] = [
	"???",
	"Bulbasaur",
	"Ivysaur",
	"Venusaur",
	"Charmander",
	"Charmeleon",
	"Charizard",
	"Squirtle",
	"Wartortle",
	"Blastoise",
	"Caterpie",
	"Metapod",
	"Butterfree",
	"Weedle",
	"Kakuna",
	"Beedrill",
	"Pidgey",
	"Pidgeotto",
	"Pidgeot",
	"Rattata",
	"Raticate",
	"Spearow",
	"Fearow",
	"Ekans",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandshrew",
	"Sandslash",
	"Nidoran♀",
	"Nidorina",
	"Nidoqueen",
	"Nidoran♂",
	"Nidorino",
	"Nidoking",
	"Clefairy",
	"Clefable",
	"Vulpix",
	"Ninetales",
	"Jigglypuff",
	"Wigglytuff",
	"Zubat",
	"Golbat",
	"Oddish",
	"Gloom",
	"Vileplume",
	"Paras",
	"Parasect",
	"Venonat",
	"Venomoth",
	"Diglett",
	"Dugtrio",
	"Meowth",
	"Persian",
	"Psyduck",
	"Golduck",
	"Mankey",
	"Primeape",
	"Growlithe",
	"Arcanine",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Abra",
	"Kadabra",
	"Alakazam",
	"Machop",
	"Machoke",
	"Machamp",
	"Bellsprout",
	"Weepinbell",
	"Victreebel",
	"Tentacool",
	"Tentacruel",
	"Geodude",
	"Graveler",
	"Golem",
	"Ponyta",
	"Rapidash",
	"Slowpoke",
	"Slowbro",
	"Magnemite",
	"Magneton",
	"Farfetch’d",
	"Doduo",
	"Dodrio",
	"Seel",
	"Dewgong",
	"Grimer",
	"Muk",
	"Shellder",
	"Cloyster",
	"Gastly",
	"Haunter",
	"Gengar",
	"Onix",
	"Drowzee",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltorb",
	"Electrode",
	"Exeggcute",
	"Exeggutor",
	"Cubone",
	"Marowak",
	"Hitmonlee",
	"Hitmonchan",
	"Lickitung",
	"Koffing",
	"Weezing",
	"Rhyhorn",
	"Rhydon",
	"Chansey",
	"Tangela",
	"Kangaskhan",
	"Horsea",
	"Seadra",
	"Goldeen",
	"Seaking",
	"Staryu",
	"Starmie",
	"Mr. Mime",
	"Scyther",
	"Jynx",
	"Electabuzz",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Magikarp",
	"Gyarados",
	"Lapras",
	"Ditto",
	"Eevee",
	"Vaporeon",
	"Jolteon",
	"Flareon",
	"Porygon",
	"Omanyte",
	"Omastar",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Snorlax",
	"Articuno",
	"Zapdos",
	"Moltres",
	"Dratini",
	"Dragonair",
	"Dragonite",
	"Mewtwo",
	"Mew",
	"Chikorita",
	"Bayleef",
	"Meganium",
	"Cyndaquil",
	"Quilava",
	"Typhlosion",
	"Totodile",
	"Croconaw",
	"Feraligatr",
	"Sentret",
	"Furret",
	"Hoothoot",
	"Noctowl",
	"Ledyba",
	"Ledian",
	"Spinarak",
	"Ariados",
	"Crobat",
	"Chinchou",
	"Lanturn",
	"Pichu",
	"Cleffa",
	"Igglybuff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Mareep",
	"Flaaffy",
	"Ampharos",
	"Bellossom",
	"Marill",
	"Azumarill",
	"Sudowoodo",
	"Politoed",
	"Hoppip",
	"Skiploom",
	"Jumpluff",
	"Aipom",
	"Sunkern",
	"Sunflora",
	"Yanma",
	"Wooper",
	"Quagsire",
	"Espeon",
	"Umbreon",
	"Murkrow",
	"Slowking",
	"Misdreavus",
	"Unown",
	"Wobbuffet",
	"Girafarig",
	"Pineco",
	"Forretress",
	"Dunsparce",
	"Gligar",
	"Steelix",
	"Snubbull",
	"Granbull",
	"Qwilfish",
	"Scizor",
	"Shuckle",
	"Heracross",
	"Sneasel",
	"Teddiursa",
	"Ursaring",
	"Slugma",
	"Magcargo",
	"Swinub",
	"Piloswine",
	"Corsola",
	"Remoraid",
	"Octillery",
	"Delibird",
	"Mantine",
	"Skarmory",
	"Houndour",
	"Houndoom",
	"Kingdra",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Stantler",
	"Smeargle",
	"Tyrogue",
	"Hitmontop",
	"Smoochum",
	"Elekid",
	"Magby",
	"Miltank",
	"Blissey",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Tyranitar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"Treecko",
	"Grovyle",
	"Sceptile",
	"Torchic",
	"Combusken",
	"Blaziken",
	"Mudkip",
	"Marshtomp",
	"Swampert",
	"Poochyena",
	"Mightyena",
	"Zigzagoon",
	"Linoone",
	"Wurmple",
	"Silcoon",
	"Beautifly",
	"Cascoon",
	"Dustox",
	"Lotad",
	"Lombre",
	"Ludicolo",
	"Seedot",
	"Nuzleaf",
	"Shiftry",
	"Taillow",
	"Swellow",
	"Wingull",
	"Pelipper",
	"Ralts",
	"Kirlia",
	"Gardevoir",
	"Surskit",
	"Masquerain",
	"Shroomish",
	"Breloom",
	"Slakoth",
	"Vigoroth",
	"Slaking",
	"Nincada",
	"Ninjask",
	"Shedinja",
	"Whismur",
	"Loudred",
	"Exploud",
	"Makuhita",
	"Hariyama",
	"Azurill",
	"Nosepass",
	"Skitty",
	"Delcatty",
	"Sableye",
	"Mawile",
	"Aron",
	"Lairon",
	"Aggron",
	"Meditite",
	"Medicham",
	"Electrike",
	"Manectric",
	"Plusle",
	"Minun",
	"Volbeat",
	"Illumise",
	"Roselia",
	"Gulpin",
	"Swalot",
	"Carvanha",
	"Sharpedo",
	"Wailmer",
	"Wailord",
	"Numel",
	"Camerupt",
	"Torkoal",
	"Spoink",
	"Grumpig",
	"Spinda",
	"Trapinch",
	"Vibrava",
	"Flygon",
	"Cacnea",
	"Cacturne",
	"Swablu",
	"Altaria",
	"Zangoose",
	"Seviper",
	"Lunatone",
	"Solrock",
	"Barboach",
	"Whiscash",
	"Corphish",
	"Crawdaunt",
	"Baltoy",
	"Claydol",
	"Lileep",
	"Cradily",
	"Anorith",
	"Armaldo",
	"Feebas",
	"Milotic",
	"Castform",
	"Kecleon",
	"Shuppet",
	"Banette",
	"Duskull",
	"Dusclops",
	"Tropius",
	"Chimecho",
	"Absol",
	"Wynaut",
	"Snorunt",
	"Glalie",
	"Spheal",
	"Sealeo",
	"Walrein",
	"Clamperl",
	"Huntail",
	"Gorebyss",
	"Relicanth",
	"Luvdisc",
	"Bagon",
	"Shelgon",
	"Salamence",
	"Beldum",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Latias",
	"Latios",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Jirachi",
	"Deoxys-Normal"
]